Repository prgrms-be-devcourse/java-calculator, pull requests merged in 2022-04, with the labels that each got.

#68 [2기-C] 김기현 1주차 java-calculator 미션 재PR입니다.
  src/main/calculator/Calculator.java
  src/test/main/calculator/CalculatorTest.java
  src/test/main/calculator/OperatorTest.java
Labels: 💧 순한맛, Team-Wook

#21 [코드리뷰요청] 1주차 java_calculator 미션 제출 - 박진형
  .idea/.gitignore
  pjh-calculator/build.gradle
  pjh-calculator/gradlew
  pjh-calculator/gradlew.bat
  pjh-calculator/settings.gradle
  pjh-calculator/src/main/java/CalculatorApplication.java
  pjh-calculator/src/main/java/calculation/CalculateService.java
  pjh-calculator/src/main/java/calculation/calculator/engine/BigDecimalCalculator.java
  pjh-calculator/src/main/java/calculation/calculator/expression/ArithmeticLogic.java
  pjh-calculator/src/main/java/calculation/calculator/expression/ExpressionService.java
  pjh-calculator/src/main/java/calculation/calculator/expression/NormalArithmeticLogic.java
  pjh-calculator/src/main/java/calculation/calculator/expression/NormalExpressionService.java
  pjh-calculator/src/main/java/calculation/io/BufferedIO.java
  pjh-calculator/src/main/java/calculation/io/Input.java
  pjh-calculator/src/main/java/calculation/io/Output.java
  pjh-calculator/src/main/java/calculation/log/CalculationLogger.java
  pjh-calculator/src/main/java/calculation/log/Logger.java
  pjh-calculator/src/main/java/calculation/log/repository/CalculationDataRepository.java
  pjh-calculator/src/main/java/calculation/log/repository/DataRepository.java
  pjh-calculator/src/main/java/calculation/model/CalculationData.java
  pjh-calculator/src/test/java/calculation/calculator/engine/BigDecimalCalculatorTest.java
  pjh-calculator/src/test/java/calculation/calculator/expression/NormalArithmeticLogicTest.java
  pjh-calculator/src/test/java/calculation/calculator/expression/NormalExpressionServiceTest.java
  pjh-calculator/src/test/java/calculation/log/CalcLogServiceTest.java
  pjh-calculator/src/test/java/calculation/log/repository/CalcDataRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#14 [이인후] 1주차 java-calculator 미션 제출
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/programmers/calculator/Calculator.java
  src/main/java/programmers/calculator/Main.java
  src/main/java/programmers/calculator/MenuOption.java
  src/main/java/programmers/calculator/controller/ControlUnit.java
  src/main/java/programmers/calculator/controller/Validator.java
  src/main/java/programmers/calculator/io/Console.java
  src/main/java/programmers/calculator/io/Input.java
  src/main/java/programmers/calculator/io/Output.java
  src/main/java/programmers/calculator/processor/Processor.java
  src/main/java/programmers/calculator/processor/arithmetic/Operator.java
  src/main/java/programmers/calculator/processor/arithmetic/Precedence.java
  src/main/java/programmers/calculator/processor/register/BufferRegister.java
  src/main/java/programmers/calculator/processor/register/OperatorRegister.java
  src/main/java/programmers/calculator/processor/register/Register.java
  src/main/java/programmers/calculator/processor/register/ResultRegister.java
  src/main/java/programmers/calculator/repository/InMemoryRepository.java
  src/main/java/programmers/calculator/repository/Repository.java
  src/test/java/programmers/calculator/MenuOptionTest.java
  src/test/java/programmers/calculator/controller/ControlUnitTest.java
  src/test/java/programmers/calculator/io/ConsoleTest.java
  src/test/java/programmers/calculator/processor/OperatorTest.java
  src/test/java/programmers/calculator/processor/ProcessorTest.java
  src/test/java/programmers/calculator/processor/register/OperatorRegisterTest.java
  src/test/java/programmers/calculator/repository/RepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon

#43 [2기-강용수] 1주차 java-calculator 미션 제출
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/AppConfig.java
  src/main/java/Application.java
  src/main/java/Calculator.java
  src/main/java/Command.java
  src/main/java/entity/Data.java
  src/main/java/io/Console.java
  src/main/java/io/Input.java
  src/main/java/io/Output.java
  src/main/java/repository/CalculatorMemoryRepository.java
  src/main/java/repository/CalculatorRepository.java
  src/main/java/service/CalculatorService.java
  src/main/java/validation/ValidateService.java
  src/test/java/repository/CalculatorRepositoryTest.java
  src/test/java/service/CalculatorServiceTest.java
  src/test/java/validation/ValidateTest.java
Labels: 🔥 매운맛, Team-Hoon

#41 [2기-C]방은혁 '계산기 TDD, OOP로 만들기'과제 코드리뷰 부탁드려요!
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/hyuk/App.java
  src/main/java/hyuk/calculator/Calculator.java
  src/main/java/hyuk/calculator/Operator.java
  src/main/java/hyuk/calculator/PostOrderFormula.java
  src/main/java/hyuk/calculator/Result.java
  src/main/java/hyuk/controller/CalculatorController.java
  src/main/java/hyuk/controller/Menu.java
  src/main/java/hyuk/entity/Record.java
  src/main/java/hyuk/model/RecordsDTO.java
  src/main/java/hyuk/model/ResultDTO.java
  src/main/java/hyuk/repository/MemoryRepository.java
  src/main/java/hyuk/repository/Repository.java
  src/main/java/hyuk/util/PatternValidator.java
  src/main/java/hyuk/view/ConsoleInputView.java
  src/main/java/hyuk/view/ConsoleOutputView.java
  src/main/java/hyuk/view/InputView.java
  src/main/java/hyuk/view/OutputView.java
  src/test/java/hyuk/calculator/CalculatorTest.java
  src/test/java/hyuk/calculator/OperatorTest.java
  src/test/java/hyuk/calculator/PostOrderFormulaTest.java
  src/test/java/hyuk/entity/RecordTest.java
  src/test/java/hyuk/repository/MemoryRepositoryTest.java
  src/test/java/hyuk/view/ConsoleInputViewTest.java
  src/test/java/hyuk/view/ConsoleOutputViewTest.java
Labels: Team-Marco, 🔥 매운맛

#53 [2기-C] 정해민 1주차 java-calculator 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/com/caculator/App.java
  src/main/java/com/caculator/Calculator.java
  src/main/java/com/caculator/ErrorMessage.java
  src/main/java/com/caculator/dto/Result.java
  src/main/java/com/caculator/io/Console.java
  src/main/java/com/caculator/io/Input.java
  src/main/java/com/caculator/io/Output.java
  src/main/java/com/caculator/repository/CalculatorRepository.java
  src/main/java/com/caculator/repository/MemoryCalculatorRepository.java
  src/main/java/com/caculator/util/Operator.java
  src/main/java/com/caculator/util/PostfixConverter.java
  src/main/java/com/caculator/util/Priority.java
  src/main/java/com/caculator/util/StringUtils.java
  src/test/java/com/caculator/CalculatorTest.java
  src/test/java/com/caculator/PostfixConverterTest.java
  src/test/java/com/caculator/repository/MemoryCalculatorRepositoryTest.java
Labels: Team-Blackdog, 🔥 매운맛

#45 [2기-C] 유도진 코드 리뷰 요청
  .gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  README.md
  app/build.gradle
  app/src/main/java/App.java
  app/src/main/java/calculator/Calculator.java
  app/src/main/java/calculator/InputParser.java
  app/src/main/java/calculator/InputValidator.java
  app/src/main/java/calculator/OPERATOR.java
  app/src/main/java/calculator/PostfixConvertor.java
  app/src/main/java/calculator/StringCalculator.java
  app/src/main/java/consoleview/ConsoleView.java
  app/src/main/java/controller/CalculatorController.java
  app/src/main/java/database/Database.java
  app/src/main/java/database/FormulaEntity.java
  app/src/test/java/calculator/CalculatorTest.java
  app/src/test/java/calculator/InputParserTest.java
  app/src/test/java/calculator/InputValidatorTest.java
  app/src/test/java/calculator/PostfixConvertorTest.java
  app/src/test/java/calculator/StringCalculatorTest.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Team-Marco, 🔥 매운맛

#62 [2기-C]정현서 '계산기 TDD, OOP로 만들기' 과제 제출
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/calculator/App.java
  src/main/java/calculator/Console.java
  src/main/java/calculator/engine/Calculator.java
  src/main/java/calculator/engine/io/Input.java
  src/main/java/calculator/engine/io/Output.java
  src/main/java/calculator/engine/model/HistoryDatabase.java
  src/main/java/calculator/engine/model/Menu.java
  src/main/java/calculator/engine/model/Operator.java
  src/main/java/calculator/engine/model/PostfixCalculator.java
  src/main/java/calculator/engine/model/PostfixConverter.java
  src/test/java/calculator/engine/model/HistoryDatabaseTest.java
  src/test/java/calculator/engine/model/OperatorTest.java
  src/test/java/calculator/engine/model/PostfixCalculatorTest.java
  src/test/java/calculator/engine/model/PostfixConverterTest.java
Labels: Team-Marco, 💧 순한맛

#75 [2기-C] 김지웅 '계산기 TDD, OOP 적용하여 만들기' 피드백 반영
  .gitignore
  app/build.gradle
  app/src/main/java/App.java
  app/src/main/java/CalculatorApp.java
  app/src/main/java/io/Console.java
  app/src/main/java/io/Input.java
  app/src/main/java/io/Output.java
  app/src/main/java/model/Expression.java
  app/src/main/java/repository/ResultRepository.java
  app/src/test/java/service/CalculateService.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Team-Marco, 💧 순한맛

#32 [2기-이수연] 1주차 java-calculator 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  img/UML.png
  settings.gradle
  src/main/java/com/programmers/project/App.java
  src/main/java/com/programmers/project/Basic.java
  src/main/java/com/programmers/project/Calculator.java
  src/main/java/com/programmers/project/Main.java
  src/main/java/com/programmers/project/Verifier.java
  src/main/java/com/programmers/project/io/Console.java
  src/main/java/com/programmers/project/io/Input.java
  src/main/java/com/programmers/project/io/Output.java
  src/main/java/com/programmers/project/repository/DataRepository.java
  src/main/java/com/programmers/project/repository/VolatilityRepository.java
  src/test/java/com/programmers/project/CalculateTest.java
  src/test/java/com/programmers/project/IOTest.java
  src/test/java/com/programmers/project/RepositoryTest.java
Labels: Team-Tyler, 🔥 매운맛

#11 [이창호] 1주차 java-calculator 미션 제출
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/App.java
  src/main/java/com/programmers/Console.java
  src/main/java/com/programmers/calculator/Calculator.java
  src/main/java/com/programmers/calculator/io/Input.java
  src/main/java/com/programmers/calculator/io/Output.java
  src/main/java/com/programmers/calculator/model/CalcData.java
  src/main/java/com/programmers/calculator/repository/MemoryRepository.java
  src/main/java/com/programmers/calculator/repository/Repository.java
  src/main/java/com/programmers/calculator/service/ArithmeticService.java
  src/main/java/com/programmers/calculator/service/ValidatorService.java
  src/test/java/com/programmers/calculator/service/ArithmeticTest.java
  src/test/java/com/programmers/calculator/service/InputTest.java
  src/test/java/com/programmers/calculator/service/SaveTest.java
  src/test/java/com/programmers/calculator/service/ValidatorTest.java
Labels: Team-Tyler, 🔥 매운맛

#76 [2기-홍유석] java-calculator 코드 리뷰 반영
  .gitignore
  README.md
  build.gradle
  settings.gradle
  src/main/java/com/calculator/java/App.java
  src/main/java/com/calculator/java/console/Console.java
  src/main/java/com/calculator/java/console/Validator.java
  src/main/java/com/calculator/java/database/Database.java
  src/main/java/com/calculator/java/engine/Calculator.java
  src/main/java/com/calculator/java/engine/comand/Commandable.java
  src/main/java/com/calculator/java/engine/comand/calculation/Calculation.java
  src/main/java/com/calculator/java/engine/comand/calculation/MathExpression.java
  src/main/java/com/calculator/java/engine/comand/inquiry/Inquiry.java
  src/main/java/com/calculator/java/global/Enum/CommandTypes.java
  src/main/java/com/calculator/java/global/Enum/Operators.java
  src/main/java/com/calculator/java/global/exception/TerminationException.java
  src/main/java/com/calculator/java/global/exception/WrongInputException.java
  src/test/java/com/calculator/java/console/ConsoleTest.java
  src/test/java/com/calculator/java/console/ValidatorTest.java
  src/test/java/com/calculator/java/database/DatabaseTest.java
  src/test/java/com/calculator/java/engine/CalculatorTest.java
  src/test/java/com/calculator/java/engine/comand/CalculationTest.java
  src/test/java/com/calculator/java/engine/comand/InquiryTest.java
Labels: Team-Victory, 🔥 매운맛

#37 [2기-정다현] 1주차 과제 "계산기 TDD, OOP로 만들기" 제출드립니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/calculator/Main.java
  src/main/java/calculator/calculate/Calculator.java
  src/main/java/calculator/calculate/CalculatorImpl.java
  src/main/java/calculator/console/Console.java
  src/main/java/calculator/dto/RequestDto.java
  src/main/java/calculator/repository/ResultRepository.java
  src/main/java/calculator/repository/ResultRepositoryImpl.java
  src/test/java/calculator/calculate/CalculatorTest.java
  src/test/java/calculator/repository/ResultRepositoryTest.java
Labels: Team-Victory, 💧 순한맛

#30 [2기-황승한] 1주차 java-calculator 미션 제출
  .gitignore
  HELP.md
  build.gradle
  settings.gradle
  src/main/java/com/programmers/calculator/CalculatorApplication.java
  src/main/java/com/programmers/calculator/engine/Calculator.java
  src/main/java/com/programmers/calculator/engine/Menu.java
  src/main/java/com/programmers/calculator/engine/Parser.java
  src/main/java/com/programmers/calculator/engine/repository/CalculatorRepository.java
  src/main/java/com/programmers/calculator/engine/repository/MemoryCalculatorRepository.java
  src/main/java/com/programmers/calculator/engine/service/CalculateService.java
  src/main/java/com/programmers/calculator/engine/service/CalculatorService.java
  src/main/java/com/programmers/calculator/engine/service/ClearService.java
  src/main/java/com/programmers/calculator/engine/service/InquiryService.java
  src/main/java/com/programmers/calculator/engine/util/ArithmeticUnit.java
  src/main/java/com/programmers/calculator/engine/util/Operator.java
  src/main/java/com/programmers/calculator/engine/util/Value.java
  src/main/java/com/programmers/calculator/io/Console.java
  src/main/java/com/programmers/calculator/io/Input.java
  src/main/java/com/programmers/calculator/io/Output.java
  src/main/resources/application.properties
  src/test/java/com/programmers/calculator/CalculatorApplicationTests.java
  src/test/java/com/programmers/calculator/ParserTest.java
  src/test/java/com/programmers/calculator/engine/ArithmeticUnitTest.java
  src/test/java/com/programmers/calculator/engine/MenuTest.java
  src/test/java/com/programmers/calculator/engine/OperatorTest.java
  src/test/java/com/programmers/calculator/engine/ValueTest.java
  src/test/java/com/programmers/calculator/engine/repository/MemoryCalculatorRepositoryTest.java
Labels: Team-Victory, 🔥 매운맛

#58 [2기-김승은] 1~2주차 java-calculator 미션 제출
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/java/App.java
  src/main/java/com/programmers/java/Console.java
  src/main/java/com/programmers/java/engine/Lobby.java
  src/main/java/com/programmers/java/engine/Menu.java
  src/main/java/com/programmers/java/engine/io/Input.java
  src/main/java/com/programmers/java/engine/io/Output.java
  src/main/java/com/programmers/java/engine/io/exception/WrongInputException.java
  src/main/java/com/programmers/java/engine/model/Calculator.java
  src/main/java/com/programmers/java/engine/model/Expression.java
  src/main/java/com/programmers/java/engine/model/History.java
  src/main/java/com/programmers/java/engine/model/Operator.java
  src/test/java/CalculatorTest.java
  src/test/java/fakeModel/FakeCalculator.java
  src/test/java/fakeModel/FakeOperator.java
Labels: Team-Victory, 🔥 매운맛
