Repository prgrms-be-devcourse/java-calculator, pull requests merged in 2023-06, with the labels that each got.

#127 [4기 -유원우] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  calculator/build.gradle
  calculator/gradle/wrapper/gradle-wrapper.jar
  calculator/gradle/wrapper/gradle-wrapper.properties
  calculator/gradlew
  calculator/gradlew.bat
  calculator/settings.gradle
  calculator/src/main/java/com/wonu606/Main.java
Labels: Team-Ray, 🔥 매운맛

#113 [4기-이근우] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/javacalculator/CalculatorApplication.java
  src/main/java/com/javacalculator/controller/CalculatorController.java
  src/main/java/com/javacalculator/docs/README.md
  src/main/java/com/javacalculator/domain/Calculator.java
  src/main/java/com/javacalculator/domain/Menu.java
  src/main/java/com/javacalculator/domain/Operator.java
  src/main/java/com/javacalculator/dto/CalculatorRequest.java
  src/main/java/com/javacalculator/util/CalculatorSplitter.java
  src/main/java/com/javacalculator/util/StringParser.java
  src/main/java/com/javacalculator/view/InputView.java
  src/main/java/com/javacalculator/view/OutputView.java
  src/main/resources/application.properties
  src/test/java/com/javacalculator/domain/CalculatorTest.java
  src/test/java/com/javacalculator/domain/MenuTest.java
  src/test/java/com/javacalculator/domain/OperatorTest.java
Labels: 🔥 매운맛, Team-Navy

#135 [4기 -유원우] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  클래스_다이어그램.png
Labels: Team-Ray, 🔥 매운맛

#137 [4기 - 김재웅] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  calculator/.gitignore
  calculator/build.gradle
  calculator/gradle/wrapper/gradle-wrapper.jar
  calculator/gradle/wrapper/gradle-wrapper.properties
  calculator/gradlew
  calculator/gradlew.bat
  calculator/settings.gradle
Labels: Team-Ray, 🔥 매운맛

#138 [4기 한승원]1~2주차 과제: 계산기 구현 미션 - 프로젝트 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Team-Ray, 🔥 매운맛

#131 [4기 - 강병곤] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/calcproject/Main.java
  src/main/java/calcproject/engine/CalcExpressionTokenizer.java
  src/main/java/calcproject/engine/Calculator.java
  src/main/java/calcproject/models/CalcRecordModel.java
  src/main/java/calcproject/repository/CalcRecordRepository.java
  src/main/java/calcproject/repository/MemoryCalcRecordRepository.java
  src/main/java/calcproject/service/CalcManager.java
  src/main/java/calcproject/view/CalcInput.java
  src/main/java/calcproject/view/CalcOutput.java
  src/main/java/calcproject/view/Command.java
  src/main/java/calcproject/view/Messages.java
  src/main/java/calcproject/view/console/CalcConsoleView.java
  src/test/java/calcproject/repository/MemoryCalcRecordRepositoryTest.java
Labels: Team-Ray, 🔥 매운맛

#155 [4기 - 김민정] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Application.java
  src/main/java/Calculator.java
  src/main/java/ConsoleInput.java
  src/main/java/ConsoleOutput.java
  src/main/java/io/Input.java
  src/main/java/io/Output.java
  src/main/java/model/Result.java
  src/main/java/utils/InputValidation.java
Labels: Team-Ray, 🔥 매운맛

#149 [4기 -유원우] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  calculator/build.gradle
  calculator/doc/기능_목록.md
  calculator/doc/클래스_다이어그램.png
  calculator/src/main/java/com/wonu606/Main.java
  calculator/src/main/java/com/wonu606/app/App.java
  calculator/src/main/java/com/wonu606/calculator/CalculatorApp.java
  calculator/src/main/java/com/wonu606/io/ConsoleInput.java
  calculator/src/main/java/com/wonu606/io/ConsolePrinter.java
  calculator/src/main/java/com/wonu606/io/Input.java
  calculator/src/main/java/com/wonu606/io/Print.java
  calculator/src/test/java/com/wonu606/io/ConsoleInputTest.java
  calculator/src/test/java/com/wonu606/io/ConsolePrinterTest.java
Labels: Team-Ray, 🔥 매운맛

#142 [4기 - 전선희] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/App.java
  src/main/java/com/programmers/BasicCalculator.java
  src/main/java/com/programmers/Console.java
  src/main/java/com/programmers/engine/JavaCalculator.java
  src/main/java/com/programmers/engine/io/Input.java
  src/main/java/com/programmers/engine/io/Output.java
  src/main/java/com/programmers/engine/model/Result.java
  src/test/java/BasicCalculatorTest.java
Labels: Team-Seunghoon

#143 [4기 - 신범철] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  docs/README.md
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/CalculatorApplication.java
  src/main/java/controller/CalculatorController.java
  src/main/java/io/CalculatorInput.java
  src/main/java/io/CalculatorOutput.java
  src/main/java/io/CalculatorPrintOutput.java
  src/main/java/io/CalculatorScannerInput.java
  src/main/java/model/vo/Expression.java
  src/main/java/model/vo/Menu.java
Labels: Team-Ray, 🔥 매운맛

#122 [4기 - 문종운] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/App.java
  src/main/java/com/programmers/calculator/Accumulator.java
  src/main/java/com/programmers/calculator/CalcResult.java
  src/main/java/com/programmers/calculator/Calculator.java
  src/main/java/com/programmers/calculator/InMemory.java
  src/main/java/com/programmers/calculator/MenuType.java
  src/main/java/com/programmers/calculator/Repository.java
  src/main/java/com/programmers/converter/ExpressionConverter.java
  src/main/java/com/programmers/converter/InfixToPostfixConverter.java
  src/main/java/com/programmers/converter/Operator.java
  src/main/java/com/programmers/converter/ResultConverter.java
  src/main/java/com/programmers/io/Console.java
  src/main/java/com/programmers/util/ConstantRegex.java
  src/main/java/com/programmers/validation/Validator.java
  src/test/java/com/programmers/calculator/AccumulatorTest.java
  src/test/java/com/programmers/calculator/InMemoryTest.java
  src/test/java/com/programmers/calculator/MenuTypeTest.java
  src/test/java/com/programmers/converter/InfixToPostfixConverterTest.java
Labels: 🔥 매운맛, Team-Navy

#123 [4기 - 김별] 1~2주차 과제 : 계산기 구현 미션 제출합니다
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/java/Main.java
  src/main/java/com/programmers/java/calculator/Calculator.java
  src/main/java/com/programmers/java/calculator/ExpressionTokenizer.java
  src/main/java/com/programmers/java/calculator/Operator.java
  src/main/java/com/programmers/java/calculator/PostfixConverter.java
  src/main/java/com/programmers/java/record/CalculationRecord.java
  src/main/java/com/programmers/java/util/OperandChecker.java
  src/main/java/com/programmers/java/view/Input.java
  src/main/java/com/programmers/java/view/Menu.java
  src/main/java/com/programmers/java/view/Output.java
  src/test/java/com/programmers/java/calculator/CalculatorTest.java
  src/test/java/com/programmers/java/calculator/PostfixConverterTest.java
  src/test/java/com/programmers/java/record/CalculationRecordTest.java
  src/test/java/com/programmers/java/util/ExpressionTokenizerTest.java
  src/test/java/com/programmers/java/view/InputTest.java
Labels: Team-Kyu, 🔥 매운맛

#162 [4기 - 김민정] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  README.md
  src/main/java/Application.java
  src/main/java/Calculator.java
  src/main/java/ConsoleOutput.java
  src/main/java/calculator/Application.java
  src/main/java/calculator/CalculateHandler.java
  src/main/java/calculator/Calculator.java
  src/main/java/calculator/ConsoleInput.java
  src/main/java/calculator/ConsoleOutput.java
  src/main/java/calculator/LookupHandler.java
  src/main/java/calculator/constant/ErrorMessage.java
  src/main/java/calculator/engine/CalculatorEngine.java
  src/main/java/calculator/handler/ICalculateHandler.java
  src/main/java/calculator/handler/ILookupHandler.java
  src/main/java/calculator/io/Input.java
  src/main/java/calculator/io/Output.java
  src/main/java/calculator/model/Result.java
  src/main/java/calculator/vo/Option.java
  src/main/java/calculator/vo/Problem.java
  src/main/java/io/Input.java
  src/main/java/io/Output.java
  src/main/java/utils/InputValidation.java
Labels: Team-Ray, 🔥 매운맛

#141 [4기-문희조] 1~2주차 과제 : 계산기 구현 미션 제출
  .gitattributes
  .gitignore
  build.gradle
  src/main/java/com/devcourse/java/App.java
  src/main/java/com/devcourse/java/common/Validator.java
  src/main/java/com/devcourse/java/domain/calculator/Calculator.java
  src/main/java/com/devcourse/java/domain/calculator/PrefixCalculator.java
  src/main/java/com/devcourse/java/domain/calculator/parser/PrefixParser.java
  src/main/java/com/devcourse/java/domain/console/Console.java
  src/main/java/com/devcourse/java/domain/console/io/ConsoleReader.java
  src/main/java/com/devcourse/java/domain/console/io/ConsoleWriter.java
  src/main/java/com/devcourse/java/domain/console/io/Reader.java
  src/main/java/com/devcourse/java/domain/console/io/Writer.java
  src/main/java/com/devcourse/java/domain/menu/Calculate.java
  src/main/java/com/devcourse/java/domain/menu/Exit.java
  src/main/java/com/devcourse/java/domain/menu/Menu.java
  src/main/java/com/devcourse/java/domain/menu/MenuMapper.java
  src/main/java/com/devcourse/java/domain/menu/MenuType.java
  src/main/java/com/devcourse/java/domain/menu/Query.java
  src/main/java/com/devcourse/java/domain/operator/Division.java
  src/main/java/com/devcourse/java/domain/operator/Minus.java
  src/main/java/com/devcourse/java/domain/operator/Multiply.java
  src/main/java/com/devcourse/java/domain/operator/Operator.java
  src/main/java/com/devcourse/java/domain/operator/OperatorMapper.java
  src/main/java/com/devcourse/java/domain/operator/OperatorType.java
  src/main/java/com/devcourse/java/domain/operator/Plus.java
  src/main/java/com/devcourse/java/domain/runner/CalculatorRunner.java
  src/main/java/com/devcourse/java/domain/storage/CalculateResult.java
  src/main/java/com/devcourse/java/domain/storage/MemoryStorage.java
  src/main/java/com/devcourse/java/domain/storage/Storage.java
  src/test/java/com/devcourse/java/domain/calculator/CalculatorTest.java
  src/test/java/com/devcourse/java/domain/mapper/MenuMapperTest.java
  src/test/java/com/devcourse/java/domain/mapper/OperatorMapperTest.java
  src/test/java/com/devcourse/java/domain/menu/MenuTest.java
  src/test/java/com/devcourse/java/domain/menu/MenuTypeTest.java
  src/test/java/com/devcourse/java/domain/operator/OperatorTest.java
  src/test/java/com/devcourse/java/domain/operator/OperatorTypeTest.java
  src/test/java/com/devcourse/java/domain/parser/ParserTest.java
  src/test/java/com/devcourse/java/domain/storage/StorageTest.java
  src/test/java/com/devcourse/java/domain/validator/ValidatorTest.java
Labels: Team-F, 🔥 매운맛

#148 [4기 - 박혜성] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/CalculatorApplication.java
  src/main/java/com/programmers/domain/Calculator.java
  src/main/java/com/programmers/domain/PostfixConverter.java
  src/main/java/com/programmers/domain/Tokenizer.java
  src/main/java/com/programmers/enumtype/Operator.java
  src/main/java/com/programmers/enumtype/ServiceSelection.java
  src/main/java/com/programmers/io/Console.java
  src/main/java/com/programmers/io/Input.java
  src/main/java/com/programmers/io/Output.java
  src/main/java/com/programmers/repository/CalculatorMemoryRepository.java
  src/main/java/com/programmers/service/CalculatorService.java
  src/main/java/com/programmers/util/Arithmetic.java
  src/test/java/com/programmers/domain/CalculatorTest.java
  src/test/java/com/programmers/domain/PostfixConverterTest.java
  src/test/java/com/programmers/domain/TokenizerTest.java
  src/test/java/com/programmers/repository/CalculationMemoryRepositoryTest.java
  src/test/java/com/programmers/service/CalculatorServiceTest.java
  src/test/java/com/programmers/util/CalculatorTestUtil.java
Labels: 🔥 매운맛, Team-Allen

#177 [4기 - 박세영] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  diagram.png
  seq_diagram.png
  settings.gradle
  src/main/java/com/devcourse/App.java
  src/main/java/com/devcourse/engine/Calculator.java
  src/main/java/com/devcourse/engine/io/InputConsole.java
  src/main/java/com/devcourse/engine/io/OutputConsole.java
  src/main/java/com/devcourse/engine/model/accepter/Accepter.java
  src/main/java/com/devcourse/engine/model/computer/Computer.java
  src/main/java/com/devcourse/engine/model/converter/Converter.java
  src/main/java/com/devcourse/engine/model/exception/InvalidInputException.java
  src/main/java/com/devcourse/engine/model/histories/Histories.java
  src/main/java/com/devcourse/engine/model/unit/Menu.java
  src/main/java/com/devcourse/engine/model/unit/Operator.java
  src/main/java/com/devcourse/engine/model/validator/Validator.java
  src/test/java/engine/computer/AccepterTest.java
  src/test/java/engine/computer/ComputerTest.java
  src/test/java/engine/computer/ConverterTest.java
  src/test/java/engine/computer/ValidatorTest.java
  src/test/java/engine/historian/HistoriesTest.java
Labels: 🔥 매운맛, Team-Allen

#181 [4기 - 김혜민] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/Application.java
  src/main/java/com/programmers/controller/CalculatorController.java
  src/main/java/com/programmers/domain/Calculator.java
  src/main/java/com/programmers/domain/CalculatorRepository.java
  src/main/java/com/programmers/domain/Expression.java
  src/main/java/com/programmers/domain/Menu.java
  src/main/java/com/programmers/domain/Operator.java
  src/main/java/com/programmers/domain/PostfixConverter.java
  src/main/java/com/programmers/domain/Repository.java
  src/main/java/com/programmers/exception/ExpressionDividedByZeroException.java
  src/main/java/com/programmers/exception/ExpressionEmptyException.java
  src/main/java/com/programmers/exception/ExpressionFormatException.java
  src/main/java/com/programmers/exception/ExpressionOtherCharacterException.java
  src/main/java/com/programmers/exception/SelectionEmptyException.java
  src/main/java/com/programmers/exception/SelectionFormatException.java
  src/main/java/com/programmers/io/Console.java
  src/main/java/com/programmers/io/Input.java
  src/main/java/com/programmers/io/Output.java
  src/test/java/com/programmers/ApplicationTest.java
  src/test/java/com/programmers/controller/CalculatorControllerTest.java
  src/test/java/com/programmers/domain/CalculatorRepositoryTest.java
  src/test/java/com/programmers/domain/CalculatorTest.java
  src/test/java/com/programmers/domain/ExpressionTest.java
  src/test/java/com/programmers/domain/MenuTest.java
  src/test/java/com/programmers/domain/OperatorTest.java
  src/test/java/com/programmers/domain/PostfixConverterTest.java
  src/test/java/com/programmers/io/ConsoleTest.java
Labels: 🔥 매운맛, Team-Allen

#182 [4기 - 최성원] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitattributes
  .gitignore
  app/build.gradle
  app/src/main/java/com/programmers/App.java
  app/src/main/java/com/programmers/calculator/Calculator.java
  app/src/main/java/com/programmers/calculator/Console.java
  app/src/main/java/com/programmers/calculator/io/Input.java
  app/src/main/java/com/programmers/calculator/io/Output.java
  app/src/main/java/com/programmers/calculator/model/Expression.java
  app/src/main/java/com/programmers/calculator/model/Operator.java
  app/src/main/java/com/programmers/calculator/repository/HistoryRepository.java
  app/src/main/java/com/programmers/calculator/util/Converter.java
  app/src/main/java/com/programmers/calculator/util/PostFixManager.java
  app/src/test/java/com/programmers/AppTest.java
  settings.gradle
  요구사항분석.md
Labels: 🔥 매운맛, Team-Allen

#183 [4기 - 김희빈] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  settings.gradle
  src/main/java/com/programmers/Application.java
  src/main/java/com/programmers/calculator/Calculator.java
  src/main/java/com/programmers/calculator/CalculatorController.java
  src/main/java/com/programmers/calculator/CalculatorRepository.java
  src/main/java/com/programmers/calculator/MemoryCalculatorRepository.java
  src/main/java/com/programmers/calculator/constant/ErrorMessage.java
  src/main/java/com/programmers/calculator/domain/CalculationResult.java
  src/main/java/com/programmers/calculator/domain/Expression.java
  src/main/java/com/programmers/calculator/domain/Menu.java
  src/main/java/com/programmers/calculator/domain/Operator.java
  src/main/java/com/programmers/calculator/exception/InvalidExpressionException.java
  src/main/java/com/programmers/calculator/exception/InvalidMenuException.java
  src/main/java/com/programmers/calculator/exception/InvalidOperatorException.java
  src/main/java/com/programmers/calculator/io/ConsoleInput.java
  src/main/java/com/programmers/calculator/io/ConsoleOutput.java
  src/main/java/com/programmers/calculator/io/Input.java
  src/main/java/com/programmers/calculator/io/Output.java
  src/main/java/com/programmers/calculator/util/PostfixConverter.java
  src/test/java/com/programmers/calculator/CalculatorTest.java
  src/test/java/com/programmers/calculator/MemoryCalculatorRepositoryTest.java
  src/test/java/com/programmers/calculator/domain/ExpressionTest.java
  src/test/java/com/programmers/calculator/domain/MenuTest.java
  src/test/java/com/programmers/calculator/domain/OperatorTest.java
  src/test/java/com/programmers/calculator/util/PostfixConverterTest.java
Labels: 🔥 매운맛, Team-Allen

#196 [4기 - 유명한] 1~2주차 과제: 잘못된 프로젝트 구조로 인해 수정 후 다시 미션 제출합니다.
  .idea/.gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/Application.java
  src/main/java/com/programmers/engine/controller/Calculator.java
  src/main/java/com/programmers/engine/exception/CalculatorErrorCode.java
  src/main/java/com/programmers/engine/exception/CalculatorException.java
  src/main/java/com/programmers/engine/io/Console.java
  src/main/java/com/programmers/engine/io/Input.java
  src/main/java/com/programmers/engine/io/Output.java
  src/main/java/com/programmers/engine/model/command/CalculationCommand.java
  src/main/java/com/programmers/engine/model/command/SelectionCommand.java
  src/main/java/com/programmers/engine/model/confirmation/Confirmation.java
  src/main/java/com/programmers/engine/model/operation/Operation.java
  src/main/java/com/programmers/engine/model/operation/Operator.java
  src/main/java/com/programmers/engine/model/stack/CalculationStack.java
  src/main/java/com/programmers/engine/model/storage/MapStorage.java
  src/main/java/com/programmers/engine/model/storage/Storage.java
  src/test/java/com/programmers/engine/MapStorageTest.java
  src/test/java/com/programmers/engine/model/OperationTest.java
  src/test/java/com/programmers/engine/model/OperatorTest.java
Labels: 🔥 매운맛, Team-Allen

#125 [4기 - 원건희] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  src/main/java/com/programmers/Application.java
  src/main/java/com/programmers/controller/CalculatorController.java
  src/main/java/com/programmers/engine/PostfixCalculator.java
  src/main/java/com/programmers/exception/BracketFormatException.java
  src/main/java/com/programmers/exception/DivideByZeroException.java
  src/main/java/com/programmers/exception/EquationFormatException.java
  src/main/java/com/programmers/exception/MenuFormatException.java
  src/main/java/com/programmers/io/Console.java
  src/main/java/com/programmers/io/Input.java
  src/main/java/com/programmers/io/Output.java
  src/main/java/com/programmers/model/UserEquation.java
  src/main/java/com/programmers/model/UserRequest.java
  src/main/java/com/programmers/repository/CalculatorHistory.java
  src/main/java/com/programmers/service/CalculatorService.java
  src/main/java/com/programmers/util/Menu.java
  src/main/java/com/programmers/util/Operator.java
  src/main/java/com/programmers/validator/InputValidator.java
  src/test/java/com/programmers/io/ConsoleTest.java
  src/test/java/com/programmers/util/OperatorTest.java
  src/test/java/com/programmers/validator/InputValidatorTest.java
Labels: 🔥 매운맛, Team-HiHi

#116 [4기 - 주홍석] 자바 계산기 구현 미션 중간 pr입니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  image.png
  settings.gradle
  src/main/java/com/devcourse/Console.java
  src/main/java/com/devcourse/Main.java
  src/main/java/com/devcourse/calc/Calculator.java
  src/main/java/com/devcourse/calc/converter/Converter.java
  src/main/java/com/devcourse/calc/converter/ConverterNoBracket.java
  src/main/java/com/devcourse/calc/converter/ConverterWithBracket.java
  src/main/java/com/devcourse/calc/model/CalculateRecord.java
  src/main/java/com/devcourse/calc/model/History.java
  src/main/java/com/devcourse/calc/model/Menu.java
  src/main/java/com/devcourse/calc/model/Operand.java
  src/main/java/com/devcourse/calc/model/Operator.java
  src/main/java/com/devcourse/calc/model/Result.java
  src/main/java/com/devcourse/calc/model/Token.java
  src/main/java/com/devcourse/calc/repo/CalcHistoryRepository.java
  src/main/java/com/devcourse/valid/FormulaValidator.java
  src/main/java/com/devcourse/valid/MenuValidator.java
  src/main/java/com/devcourse/view/Input.java
  src/main/java/com/devcourse/view/Output.java
  src/test/java/com/devcourse/calc/CalculatorTest.java
  src/test/java/com/devcourse/calc/converter/ConverterNoBracketTest.java
  src/test/java/com/devcourse/calc/model/MenuTest.java
  src/test/java/com/devcourse/calc/model/OperatorTest.java
  src/test/java/com/devcourse/valid/FormulaValidatorTest.java
Labels: Team-Kyu, 🔥 매운맛

#192 [4기 - 신재윤] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  docs/README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/Application.java
  src/main/java/com/programmers/calculator/constant/OptionType.java
  src/main/java/com/programmers/calculator/constant/RegexEnum.java
  src/main/java/com/programmers/calculator/controller/CalculatorController.java
  src/main/java/com/programmers/calculator/domain/component/Evaluator.java
  src/main/java/com/programmers/calculator/domain/component/NotationConverter.java
  src/main/java/com/programmers/calculator/domain/component/PostfixConverter.java
  src/main/java/com/programmers/calculator/domain/component/PostfixEvaluator.java
  src/main/java/com/programmers/calculator/domain/core/Calculator.java
  src/main/java/com/programmers/calculator/domain/core/FourArithmeticCalculator.java
  src/main/java/com/programmers/calculator/domain/core/Operator.java
  src/main/java/com/programmers/calculator/domain/vo/CalculationResult.java
  src/main/java/com/programmers/calculator/domain/vo/Expression.java
  src/main/java/com/programmers/calculator/repository/CalculationHistory.java
  src/main/java/com/programmers/calculator/repository/HistoryMapRepository.java
  src/main/java/com/programmers/calculator/repository/HistoryRepository.java
  src/main/java/com/programmers/calculator/view/Console.java
  src/main/java/com/programmers/calculator/view/Input.java
  src/main/java/com/programmers/calculator/view/InputReader.java
  src/main/java/com/programmers/calculator/view/Output.java
  src/main/java/com/programmers/calculator/view/OutputWriter.java
  src/test/java/com/programmers/calculator/constant/OptionTypeTest.java
  src/test/java/com/programmers/calculator/constant/RegexEnumTest.java
  src/test/java/com/programmers/calculator/domain/component/PostfixConverterTest.java
  src/test/java/com/programmers/calculator/domain/component/PostfixEvaluatorTest.java
  src/test/java/com/programmers/calculator/domain/core/FourArithmeticCalculatorTest.java
  src/test/java/com/programmers/calculator/domain/core/OperatorTest.java
  src/test/java/com/programmers/calculator/repository/HistoryMapRepositoryTest.java
Labels: Team-Blackdog, 🔥 매운맛

#146 [4기 - 윤영운] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/example/App.java
  src/main/java/org/example/compute/ArithmeticCompute.java
  src/main/java/org/example/compute/Compute.java
  src/main/java/org/example/controller/CalculatorController.java
  src/main/java/org/example/exception/BadEquationException.java
  src/main/java/org/example/io/ConsoleInput.java
  src/main/java/org/example/io/ConsoleOutput.java
  src/main/java/org/example/io/Input.java
  src/main/java/org/example/io/Output.java
  src/main/java/org/example/repository/EquationRepository.java
  src/main/java/org/example/repository/MemoryEquationRepository.java
  src/main/java/org/example/util/CheckEquation.java
  src/main/java/org/example/util/InputStringFormating.java
  src/main/java/org/example/util/Menu.java
  src/main/java/org/example/util/Operator.java
  src/test/java/org/example/compute/ArithmeticComputeTest.java
  src/test/java/org/example/controller/CalculatorControllerTest.java
  src/test/java/org/example/repository/MemoryEquationRepositoryTest.java
  src/test/java/org/example/util/CheckEquationTest.java
Labels: 🔥 매운맛, Team-HiHi

#124 [4기 - 황창현] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/org/programmers/java/App.java
  src/main/java/org/programmers/java/Calculator.java
  src/main/java/org/programmers/java/calculation/Calculation.java
  src/main/java/org/programmers/java/calculation/InfixToPostfixConverter.java
  src/main/java/org/programmers/java/calculation/Operator.java
  src/main/java/org/programmers/java/calculation/PostfixCalculation.java
  src/main/java/org/programmers/java/console/Console.java
  src/main/java/org/programmers/java/console/Input.java
  src/main/java/org/programmers/java/console/Output.java
  src/main/java/org/programmers/java/docs/README.md
  src/main/java/org/programmers/java/message/Error.java
  src/main/java/org/programmers/java/message/FunctionSelect.java
  src/main/java/org/programmers/java/message/Info.java
  src/main/java/org/programmers/java/repository/FormulaMemoryRepository.java
  src/main/java/org/programmers/java/repository/FormulaRepository.java
  src/main/java/org/programmers/java/validator/Validator.java
  src/test/java/org/programmers/java/CalculationTest.java
  src/test/java/org/programmers/java/OperatorTest.java
  src/test/java/org/programmers/java/RepositoryTest.java
  src/test/java/org/programmers/java/ValidaionTest.java
Labels: 🔥 매운맛, Team-Navy

#179 [4기 - 박이슬] 1~2주차 과제: 계산기 구현 미션 제출입니다.
  .gitignore
  README.md
  build.gradle
  settings.gradle
  src/main/java/com/programmers/java/calculator/CalculatorApplication.java
  src/main/java/com/programmers/java/calculator/controller/CalculatorController.java
  src/main/java/com/programmers/java/calculator/docs/README.md
  src/main/java/com/programmers/java/calculator/domain/CalculationHistory.java
  src/main/java/com/programmers/java/calculator/domain/MenuType.java
  src/main/java/com/programmers/java/calculator/domain/Operator.java
  src/main/java/com/programmers/java/calculator/domain/calculator/Calculator.java
  src/main/java/com/programmers/java/calculator/domain/calculator/PostfixExpressionCalculator.java
  src/main/java/com/programmers/java/calculator/repository/CalculatorRepository.java
  src/main/java/com/programmers/java/calculator/repository/MemoryCalculatorRepository.java
  src/main/java/com/programmers/java/calculator/service/CalculatorService.java
  src/main/java/com/programmers/java/calculator/util/Converter.java
  src/main/java/com/programmers/java/calculator/util/PostfixExpressionConverter.java
  src/main/java/com/programmers/java/calculator/view/Console.java
  src/main/java/com/programmers/java/calculator/view/Input.java
  src/main/java/com/programmers/java/calculator/view/Output.java
  src/test/java/com/programmers/java/calculator/CalculationTest.java
  src/test/java/com/programmers/java/calculator/MenuSelectionTest.java
  src/test/java/com/programmers/java/calculator/OperatorTest.java
Labels: 🔥 매운맛, Team-Navy

#176 [4기 - 김민희] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/com/programmers/Main.java
  src/main/java/com/programmers/controller/CalculatorController.java
  src/main/java/com/programmers/domain/Menu.java
  src/main/java/com/programmers/domain/Operator.java
  src/main/java/com/programmers/error/CalculatorException.java
  src/main/java/com/programmers/error/ConsoleMessage.java
  src/main/java/com/programmers/error/ErrorMessage.java
  src/main/java/com/programmers/model/ExpressionResult.java
  src/main/java/com/programmers/repository/CalculatorRepository.java
  src/main/java/com/programmers/repository/MapCalculatorRepository.java
  src/main/java/com/programmers/service/CalculatorService.java
  src/main/java/com/programmers/util/CalculatorProcessor.java
  src/main/java/com/programmers/util/IdGenerator.java
  src/main/java/com/programmers/util/Validator.java
  src/main/java/com/programmers/view/Input.java
  src/main/java/com/programmers/view/Output.java
  src/test/java/domain/OperatorTest.java
  src/test/java/io/InputTest.java
  src/test/java/repository/CalculatorRepositoryTest.java
  src/test/java/service/CalculatorServiceTest.java
Labels: 🔥 매운맛, Team-Navy

#197 [4기 - 민승현] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  settings.gradle
  src/main/java/org/programmers/Application.java
  src/main/java/org/programmers/Io/Console.java
  src/main/java/org/programmers/Io/Input.java
  src/main/java/org/programmers/Io/Output.java
  src/main/java/org/programmers/calculator/Calculate.java
  src/main/java/org/programmers/calculator/Calculator.java
  src/main/java/org/programmers/calculator/Operator.java
  src/main/java/org/programmers/calculator/Option.java
  src/main/java/org/programmers/repository/CalRepository.java
  src/main/java/org/programmers/repository/CalRepositoryImpl.java
  src/main/java/org/programmers/validator/Validator.java
  src/test/java/org/programmers/calculator/OperatorTest.java
  src/test/java/org/programmers/calculator/calculateTest.java
  src/test/java/org/programmers/repository/CalRepositoryTest.java
  src/test/java/org/programmers/validator/ValidatorTest.java
Labels: Team-Blackdog, 🔥 매운맛

#173 [4기 - 양정우] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/calculator/CalculatorApplication.java
  src/main/java/calculator/calculator/CalculatorController.java
  src/main/java/calculator/domain/Expression.java
  src/main/java/calculator/domain/enums/Command.java
  src/main/java/calculator/domain/enums/Operator.java
  src/main/java/calculator/domain/repository/CalculatorRepository.java
  src/main/java/calculator/exception/ApplicationException.java
  src/main/java/calculator/exception/ErrorMessage.java
  src/main/java/calculator/service/CalculatorProcessor.java
  src/main/java/calculator/service/CalculatorService.java
  src/main/java/calculator/view/InputView.java
  src/main/java/calculator/view/OutputView.java
  src/test/java/calculator/domain/CommandTest.java
  src/test/java/calculator/domain/ExpressionTest.java
  src/test/java/calculator/domain/OperatorTest.java
  src/test/java/calculator/domain/repository/CalculatorRepositoryTest.java
  src/test/java/calculator/service/CalculatorProcessorTest.java
Labels: Team-F, 🔥 매운맛

#178 [4기 - 이성주] 1~2주차 과제: 계산기 구현 미션 제출입니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/devcourse/App.java
  src/main/java/org/devcourse/calculator/Calculator.java
  src/main/java/org/devcourse/calculator/ExpressionConverter.java
  src/main/java/org/devcourse/calculator/MenuType.java
  src/main/java/org/devcourse/exception/InputExpressionException.java
  src/main/java/org/devcourse/exception/MenuTypeException.java
  src/main/java/org/devcourse/io/ConsoleDevice.java
  src/main/java/org/devcourse/io/IODevice.java
  src/main/java/org/devcourse/repository/MemoryRepository.java
  src/main/java/org/devcourse/repository/Repository.java
  src/main/java/org/devcourse/util/DigitChecker.java
  src/main/java/org/devcourse/util/RegexPattern.java
  src/main/java/org/devcourse/validator/ExpressionValidator.java
  src/main/java/org/devcourse/validator/MenuValidator.java
  src/main/java/org/devcourse/validator/Validator.java
  src/test/java/org/devcourse/calculator/ExpressionConverterTest.java
  src/test/java/org/devcourse/repository/MemoryRepositoryTest.java
  src/test/java/org/devcourse/validator/ExpressionValidatorTest.java
  src/test/java/org/devcourse/validator/MenuValidatorTest.java
Labels: Team-F, 🔥 매운맛

#121 [4기 - 고예성] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/Application.java
  src/main/java/Processor.java
  src/main/java/exception/IllegalExpressionException.java
  src/main/java/exception/NoSuchCommandException.java
  src/main/java/exception/NoSuchOperatorException.java
  src/main/java/model/Calculator.java
  src/main/java/model/HistoryStorage.java
  src/main/java/model/Operator.java
  src/main/java/util/CalculatorUtils.java
  src/main/java/view/Command.java
  src/main/java/view/View.java
  src/main/resources/자바 계산기 구현미션-6.jpg
  src/test/java/model/CalculatorTest.java
  src/test/java/model/HistoryStorageTest.java
  src/test/java/model/OperatorTest.java
  src/test/java/view/CommandTest.java
Labels: Team-Kyu, 🔥 매운맛

#164 [4기 - 이현호] 1~2주차 과제: 계산기 구현 미션 제출합니다.
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/example/Main.java
  src/main/java/org/example/controller/CalculatorSystem.java
  src/main/java/org/example/domain/CalculateExecuter.java
  src/main/java/org/example/domain/Calculator.java
  src/main/java/org/example/domain/ExpressionConvertor.java
  src/main/java/org/example/domain/History.java
  src/main/java/org/example/domain/HistoryInterface.java
  src/main/java/org/example/util/Command.java
  src/main/java/org/example/util/Operator.java
  src/main/java/org/example/validate/Validater.java
  src/main/java/org/example/view/CalculatorView.java
  src/main/java/org/example/view/InputView.java
  src/main/java/org/example/view/OutputView.java
  src/test/java/org/example/domain/CalculatorTest.java
Labels: 🔥 매운맛, Team-HiHi

#126 [4기 - 박세연] 1~2주차 과제 : 계산기 구현 미션 제출합니다.
  .gitignore
  build.gradle
  docs/README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/CalculatorApplication.java
  src/main/java/calculator/controller/CalculatorController.java
  src/main/java/calculator/domain/Calculate.java
  src/main/java/calculator/domain/Calculator.java
  src/main/java/calculator/domain/PostFixCalculate.java
  src/main/java/calculator/repository/CalculatorRepository.java
  src/main/java/calculator/service/CalculatorService.java
  src/main/java/ui/InputView.java
  src/main/java/ui/OutputView.java
  src/main/java/util/Brackets.java
  src/main/java/util/ExceptionMsg.java
  src/main/java/util/IllegalException.java
  src/main/java/util/Menu.java
  src/main/java/util/OperatorMap.java
  src/main/java/util/ValidationEquation.java
  src/main/java/util/ValidationInput.java
  src/main/java/util/model/CalculateRequest.java
  src/test/java/calculator/domain/CalculatorTest.java
  src/test/java/calculator/domain/PostCalculatorTest.java
  src/test/java/calculator/repository/CalculatorRepositoryTest.java
  src/test/java/calculator/service/CalculatorServiceTest.java
  src/test/java/calculator/ui/InputViewTest.java
Labels: 🔥 매운맛, Team-HiHi

#134 [4기 - 김영주] 1~2주차 과제: 계산기 구현 미션 제출합니다. (5차)
  .gitattributes
  .gitignore
  README.md
  app/build.gradle
  app/src/main/java/calculator/App.java
  app/src/main/java/calculator/controller/MainController.java
  app/src/main/java/calculator/entity/Expression.java
  app/src/main/java/calculator/entity/InfixNotation.java
  app/src/main/java/calculator/entity/Menu.java
  app/src/main/java/calculator/entity/Notation.java
  app/src/main/java/calculator/entity/Operator.java
  app/src/main/java/calculator/entity/PostfixNotation.java
  app/src/main/java/calculator/exception/ExpressionInputException.java
  app/src/main/java/calculator/exception/MenuInputException.java
  app/src/main/java/calculator/service/Calculator.java
  app/src/main/java/calculator/storage/HistoryStorage.java
  app/src/main/java/calculator/utils/StringUtils.java
  app/src/main/java/calculator/view/InputView.java
  app/src/main/java/calculator/view/OutputView.java
  app/src/test/java/calculator/service/InfixCalculatorTest.java
  app/src/test/java/calculator/service/PostfixCalculatorTest.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Team-Kyu, 🔥 매운맛

#160 [4기 - 조재현] 자바 계산기 구현 미션 7번째(마지막) pr입니다.
  .DS_Store
  .gitignore
  README.md
  build.gradle
  build/.DS_Store
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/.DS_Store
  src/main/java/org/example/Main.java
  src/main/java/org/example/domain/CalculateType.java
  src/main/java/org/example/domain/Calculator.java
  src/main/java/org/example/domain/Console.java
  src/main/java/org/example/exception/Exception.java
  src/main/java/org/example/repository/Records.java
  src/main/java/org/example/view/Input.java
  src/main/java/org/example/view/Output.java
  src/main/java/org/example/view/SelectTypeView.java
  src/main/java/org/example/view/View.java
  src/test/java/calculate/CalculatorTest.java
Labels: Team-Kyu, 🔥 매운맛
